// Send the brief as a nicely-formatted HTML email via Resend.
// Falls back to console output if no Resend key is set (useful for testing).

import { Resend } from "resend";
import { marked } from "marked";

const FROM = process.env.EMAIL_FROM || "Learning App <briefs@resend.dev>";
const TO = process.env.RECIPIENT_EMAIL;

/**
 * @param {object} arg
 * @param {string} arg.subject
 * @param {string} arg.markdown — body in Markdown
 */
export async function sendEmail({ subject, markdown }) {
  if (!TO) throw new Error("RECIPIENT_EMAIL not set");

  const html = wrapHtml(marked.parse(markdown));

  if (!process.env.RESEND_API_KEY) {
    console.log("[email] RESEND_API_KEY not set — dumping subject+body to stdout instead.");
    console.log("Subject:", subject);
    console.log(markdown);
    return;
  }

  const resend = new Resend(process.env.RESEND_API_KEY);
  const { error } = await resend.emails.send({
    from: FROM,
    to: [TO],
    subject,
    html,
    text: markdown,
  });
  if (error) throw new Error(`Resend error: ${error.message || JSON.stringify(error)}`);
  console.log(`[email] sent "${subject}" -> ${TO}`);
}

function wrapHtml(inner) {
  return `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #1f2937;
         line-height: 1.55; max-width: 640px; margin: 0 auto; padding: 24px 20px; background: #fafaf9; }
  h1, h2, h3 { letter-spacing: -0.01em; }
  h1 { font-size: 22px; margin-top: 0; }
  h2 { font-size: 17px; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; margin-top: 28px; }
  h3 { font-size: 14px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.06em; margin-top: 22px; }
  a { color: #b45309; }
  ul { padding-left: 22px; } li { margin: 4px 0; }
  blockquote { border-left: 3px solid #f59e0b; padding: 2px 12px; color: #4b5563; margin: 12px 0; }
  code { background: #f3f4f6; padding: 1px 5px; border-radius: 4px; font-size: 13px; }
  hr { border: none; border-top: 1px solid #e5e7eb; margin: 24px 0; }
  .footer { color: #9ca3af; font-size: 12px; margin-top: 30px; text-align: center; }
</style></head><body>
${inner}
<div class="footer">Generated by your learning-backlog cron · Reply to this email to send feedback into the void</div>
</body></html>`;
}
